### ISSUE TITLE
Train TypeError: Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by Bonjur** [krystianity/coinpusher#1]
Hi just the train is not working.
Curl gives {"message":"failed"}
----------------------------------------
 coinpusher:coinstream trade btceur 126.4185579774 0 +2s
  coinpusher:main fork 2017-10-26T05:43:11.191Z coinpusher:jobs:train TypeError: Cannot read property 'x' of undefined
    at NeuronalNetworkFactory.createNewNetwork (E:\coinpusher\lib\NeuronalNetworkFactory.js:79:54)
    at _getDatasetForCurrency.then.dataset (E:\coinpusher\lib\jobs\train.js:45:30)
    at tryCatcher (E:\coinpusher\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\coinpusher\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (E:\coinpusher\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (E:\coinpusher\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (E:\coinpusher\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (E:\coinpusher\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (E:\coinpusher\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (E:\coinpusher\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
 +723ms
  coinpusher:main failed to train network 3 +17ms
  coinpusher:coinstream trade btceur 194.4155438824 0 +2s

**Comment by Bonjur** [comment]
fixed

**Comment by krystianity** [comment]
Yeah, this can sometimes happen if you havent "waited long enough" for the first chunks of data to be written to the stream file. Sometimes it takes a while as live trades are used as source. If you just want to try it out, the best idea is to start with BTC_USD or BTC_EUR these currency-pairs have a lot of trades per minute on bitstamp. Wait for a few minutes and the dataset should contain of at least 20 trades.

**Comment by imkane** [comment]
Oops, this may be my issue too #2 lol. I'll try to be more patient!
