### ISSUE TITLE
curl http://localhost:3333/nn/train/btceur {"message":"failed"}

### ISSUE THREAD

**Issue by SPIRY-RO** [krystianity/coinpusher#11]
What is the issue here?
```

 fork 2018-07-28T23:02:30.698Z coinpusher:jobs:train TypeError: Cannot read property 'x' of undefined
    at NeuronalNetworkFactory.createNewNetwork (/root/tradingOP/Nostradamus/lib/NeuronalNetworkFactory.js:79:54)
    at _getDatasetForCurrency.then.dataset (/root/tradingOP/Nostradamus/lib/jobs/train.js:45:30)
    at tryCatcher (/root/tradingOP/Nostradamus/node_modules/bluebird/js/release/util.js:16:23)

```

**Comment by born2hate** [comment]
i got the same, any help?

**Comment by born2hate** [comment]
need to wait about 10 mins, solved ;)

**Comment by vedanksingh** [comment]
Can anyone guide me i have downloaded this repo what i have to do after that
