### ISSUE TITLE
Use USD currency?

### ISSUE THREAD

**Issue by imkane** [krystianity/coinpusher#2]
This looks really promising, thanks for sharing it!

Maybe a dumb question, but what's the easiest way to switch from "eur" to "usd"?

Cheers!

**Comment by imkane** [comment]
FYI I tried doing the old-school method of find-replace, but when running:

`curl http://127.0.0.1:3334/nn/train/ethusd`

I get in my other session window:

```
coinpusher:socketserver express hit /nn/train/ethusd +16s
  coinpusher:main fork 2017-11-16T22:44:03.351Z coinpusher:coinstream stream loaded ethusd 21.254 kb 106
 +16s
  coinpusher:main fork 2017-11-16T22:44:03.354Z coinpusher:networkfactory creating new net
 +3ms
  coinpusher:main fork 2017-11-16T22:44:04.152Z coinpusher:jobs:train TypeError: Cannot read property 'x' of undefined
    at NeuronalNetworkFactory.createNewNetwork (/home/coinpusher/lib/NeuronalNetworkFactory.js:79:54)
    at _getDatasetForCurrency.then.dataset (/home/coinpusher/lib/jobs/train.js:45:30)
    at tryCatcher (/home/coinpusher/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/coinpusher/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/coinpusher/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/coinpusher/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/coinpusher/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/coinpusher/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/coinpusher/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/coinpusher/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
 +797ms
  coinpusher:main failed to train network 3 +6ms
```

**Comment by imkane** [comment]
Regarding the training error, I just had to wait about 30 min or so and it worked :)

**Comment by ddey94** [comment]
@imkane  Can you please explain what exactly you did to convert from eur to usd?

**Comment by imkane** [comment]
@ddey94 basically just a find-replace in all the code lol. Not very elegant but it seemed to work.
